### PR TITLE
Fix Specific volume second derivative SA P mistake (from Matlab)

### LINKED ISSUE #52: Specific volume second derivative SA P mistake (from Matlab)
See https://github.com/TEOS-10/GSW-Matlab/commit/38c9635d6fd93e74c2648e4ee23cec49c1f58530 in the Matlab repo. This should be updated through downstream repos.

### PR DESCRIPTION
**Pull request by ocefpaf**
Port https://github.com/TEOS-10/GSW-Matlab/commit/38c9635d6fd93e74c2648e4ee23cec49c1f58530

Thanks @richardsc for pointing this out.

Closes #52 

---
We need to update the test values for:

```
specvol_second_derivatives (v_sa_p)........................... << failed >>
rho_second_derivatives (rho_sa_p)............................. << failed >>
thermobaric................................................... << failed >>
```

### CODE REVIEW

**Comment by ocefpaf** [comment]
If I update to the latest matlab file we fix those but get more errors, probably other updates that got dumped in the matlab code.

```
c_from_sp..................................................... << failed >>
sp_from_c..................................................... << failed >>
specvol_second_derivatives_wrt_enthalpy (v_sa_sa_wrt_h)....... << failed >>
rho_second_derivatives_wrt_enthalpy (rho_sa_sa_wrt_h)......... << failed >>
geo_strf_dyn_height........................................... << failed >>
```

**Comment by ocefpaf** [comment]
Commit https://github.com/TEOS-10/GSW-C/pull/53/commits/d8c48ed214e114bfb150e7ca6a352a531484b820 fixed these:

```
specvol_second_derivatives_wrt_enthalpy (v_sa_sa_wrt_h)....... << failed >>
rho_second_derivatives_wrt_enthalpy (rho_sa_sa_wrt_h)......... << failed >>
```
3 more to go!

**Comment by castelao** [comment]
Good catch on [d8c48ed](https://github.com/TEOS-10/GSW-C/pull/53/commits/d8c48ed214e114bfb150e7ca6a352a531484b820)

**Comment by efiring** [comment]
geo_strf_dyn_height is expected to fail with the matlab check values; we are using a different algorithm, so we need to patch in our own check values.  See #36.

**Comment by efiring** [comment]
Are the data and check values in this PR now coming from gsw_matlab_v3_06_16.zip?

**Comment by ocefpaf** [comment]
> Are the data and check values in this PR now coming from gsw_matlab_v3_06_16.zip?

[Yep](https://github.com/TEOS-10/GSW-C/blob/c3420786eba80c29236bf248d34755a526969ffd/gsw_check_data.h#L4). Downloaded from https://www.teos-10.org/software/gsw_matlab_v3_06_16.zip and sent as a PR to https://github.com/TEOS-10/GSW-Matlab/pull/15 for tracking purposes.

> geo_strf_dyn_height is expected to fail with the matlab check values; we are using a different algorithm, so we need to patch in our own check values. See #36.

I thought that the check data https://github.com/TEOS-10/GSW-C/blob/b5ecb2a9d4adbe123cfe7b098b2288a2db82e8f5/make_data_from_mat.py#L334-L336 patched it. I use that script to create the new data.

**Comment by efiring** [comment]
You are correct, running make_data_from_mat.py should take care of the patch, *provided* none of the inputs to the test have changed.
I also did a quick check to compare the constants and code in sp_from_c between our version and the matlab, and I don't see anything that could account for the difference.  This might take some deep digging, starting with isolating a single set of input check values out of the whole array being tested.

**Comment by efiring** [comment]
I'm making some progress in tracking it down; it looks like a change in the check values for conductivity in the fresh-water case; the failure now is occurring in a value that was masked before.

**Comment by PaulMBarker** [comment]
I do not remember changing the code in SP_from_C or C_from _SP. 
The check values should not have changed unless I have accidently entered something.

**Comment by castelao** [comment]
@PaulMBarker , just to clarify. The check values should be the same, but would those be still adequate to validate `SP_from_C` and `C_from_SP` after you changed the code?

It's intriguing. I'm using the data from 3_06_16 to validate those functions in [Rust](https://github.com/castelao/GSW-rs/blob/main/tests/practical_salinity.rs) with success. It is interesting that in other functions I can match the validation dataset with precision epsilon, but in this group of functions the difference was slightly larger.

**Comment by PaulMBarker** [comment]
If your code matches my matlab code then the values will be correct.
Did you find a change? if so what was it?

**Comment by efiring** [comment]
@PaulMBarker The comparisons here are between what was in the gsw_matlab_v3_06_11 zipfile and the gsw_matlab_v3_06_16 zipfile.
The gsw_C_from_SP.m code has not changed (apart from the comment giving the date).
The values in the *chck_cast arrays (with 3 profiles each) have changed by fairly small amounts; I have no idea why.
Correspondingly, the check values have also changed by similarly small amounts.

The failures in the two tests in the C code, for C_from_SP and SP_from_C are *not* related to the
ubiquitous small changes described above.  Instead, they arise from a different change in the check values for
C_from_SP, specifically in the 3rd column, the short "cast" in fresh water (SP=0). In the _11 version, the first 6 of
those check values are nan, and are followed by 2 non-nan values; in the _16 version, all 8 fresh-water
check values are non-nan.  So, previously in the C code, only the last 2 of the fresh-water calculations of C
were being tested, but now all 8 of them are, and some of those 8 are failing.

I have not yet looked closely at the low-S part of the C code in C_from_SP to see whether it is somehow different from  
the matlab version, and I have not determined how many of the 8 values are failing.  I know the first one (for P=0) is
failing, and has the maximum error (which is still very small, but well beyond the given tolerance).

Once C_from_SP has failed, it is inevitable that SP_from_C will also fail, since the latter is using the output of the former.

**Comment by castelao** [comment]
@efiring and @PaulMBarker , thanks for the info.

**Comment by efiring** [comment]
I have found the problem: a difference in the sign of coefficient q7.
@ocefpaf, can I push to this branch on your repo?  I also need to fix the check values for geo_strf_dyn_height,
which is most easily done by putting all the C updates and fixups in GSW-Python first.  I also have a small change
to the C gsw_check executable that makes debugging a little easier when problems like this arise.

**Comment by ocefpaf** [comment]
> I have found the problem: a difference in the sign of coefficient q7.
@ocefpaf, can I push to this branch on your repo?

Done!

> I also need to fix the check values for geo_strf_dyn_height,
which is most easily done by putting all the C updates and fixups in GSW-Python first. I also have a small change
to the C gsw_check executable that makes debugging a little easier when problems like this arise.

If you don't mind let's merge this one as-is then, with only the `geo_strf_dyn_height` failure now, and fix the rest on a new PR.

**Review by efiring — APPROVED** [review]

**Pull request merged**
