### PR TITLE
add GHA for compilation and testing

### PR DESCRIPTION
**Pull request by ocefpaf**
@efiring I may need some help on how you test this locally. We do not have a `make check`, right?

### CODE REVIEW

**Comment by efiring** [comment]
There is no "make check", just the gsw_check executable.  It currently returns zero regardless of whether it fails or succeeds.  Making it return 1 (for example)  on failure requires changing

```C
        if (gsw_error_flag)
            printf("\nYour installation of the Gibbs SeaWater (GSW) "
                "Oceanographic Toolbox has errors !\n");
        else
```
to
```C
        if (gsw_error_flag)
        {
            printf("\nYour installation of the Gibbs SeaWater (GSW) "
                "Oceanographic Toolbox has errors !\n");
            return (1);
        }
        else
```
in gsw_check_functions.c.

**Comment by ocefpaf** [comment]
I can make the changes later this week. Working on setting the compiler config up first.

**Comment by DocOtak** [comment]
I took a crack at having a non zero exit status in #43 

If you want just cherrypick that code and stick it in this PR.

**Comment by ocefpaf** [comment]
It is late for me and I'm on my phone. It is OK to merge your PR and I'll rebase this PR tomorrow.

Thnaks!

**Comment by efiring** [comment]
For Linux/OSX we need to run "make -f Makefile", not just plain "make", so that Makefile will be used instead of GNUmakefile. Or remove (or move) GNUmakefile, which is obsolete; it has features specific to its origin at SIO.  It shows how to do some things that someone might want, so instead of deleting it, perhaps it should be moved to "GNUmakefile.example".

**Comment by ocefpaf** [comment]
@DocOtak and @efiring this is ready for review. I tested it by breaking the code and the CIs failed as expected. Thanks @DocOtak for #43!

PS: the Windows one is also working. I have a draft in #44

**Review by efiring — APPROVED** [review]

**Pull request merged**
