### PR TITLE
Windows compiler support

### PR DESCRIPTION
**Pull request by egecetin**
Since MS Compiler does not fully support C99 features, complex mathematical function wrappers are provided. It may be a separate branch from master due to the complexity of changing functions.

Tested with MSVC 19.29.30038.1

### CODE REVIEW

**Comment by efiring** [comment]
Why are you doing this? In master, the deficiencies of the MSC compiler are handled by using C++ instead.  Doesn't that work for you?

**Comment by egecetin** [comment]
Yes it works, but it might be an option if for some reason only a pure c solution is needed. As I said in the comment, the merge might be unreasonable due to complexity but might be another branch.

**Comment by efiring** [comment]
I don't know of any reason why a pure-C approach would be needed, do you?  The C++ is used only for Windows, and even for Windows, I think the resulting library is accessed exactly as if it were all C because of the 'extern "C"' declaration in gswteos-10.h.

I think that what we are really missing is just Makefile logic for MS, plus github actions to run the build and test suite. If the Makefile has to be very different, then I would prefer a separate Makefile to be specified on the command line for MS, instead of making the existing Makefile too complex. I definitely don't want to bring in Cmake.

**Comment by egecetin** [comment]
Well, then the request can be closed.

**Pull request closed without merging**
